# Global app configurations

MAIN_WINDOW_WIDTH = 350
MAIN_WINDOW_HEIGHT = 500

IMAGES_WINDOW_WIDTH = 640
IMAGES_WINDOW_HEIGHT = 480

AI_WINDOW_WIDTH = 800
AI_WINDOW_HEIGHT = 500

ALLOWED_IMAGE_FILE_TYPES = [".jpg", ".jpeg", ".png"]
